spring:
    application:
        name: ProjectRestaurants
    datasource:
        url: jdbc:mysql://localhost:3306/restaurant_db
        password: 123456789d
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl:
                auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    liquibase:
        change-log: classpath:/db/changelog/app-changelog.xml
        default-schema: restaurant_db