INSERT INTO permissions (action_name)
VALUES ("USER_DELETE"),
       ("RESTAURANT_CREATE"),
       ("RESTAURANT_READ"),
       ("RESTAURANT_UPDATE"),
       ("RESTAURANT_DELETE"),
       ("RECIPE_CREATE"),
       ("RECIPE_READ"),
       ("RECIPE_UPDATE"),
       ("RECIPE_DELETE"),
       ("PRODUCT_CREATE"),
       ("PRODUCT_READ"),
       ("PRODUCT_UPDATE"),
       ("PRODUCT_DELETE"),
       ("ORDER_CREATE"),
       ("ORDER_READ"),
       ("ORDER_UPDATE"),
       ("ORDER_DELETE"),
       ("MENU_CREATE"),
       ("MENU_READ"),
       ("MENU_UPDATE"),
       ("MENU_DELETE"),
       ("EXPIRE_CREATE"),
       ("EXPIRE_READ"),
       ("EXPIRE_UPDATE"),
       ("EXPIRE_DELETE"),
       ("DISH_CREATE "),
       ("DISH_READ"),
       ("DISH_UPDATE"),
       ("DISH_DELETE");